# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: TestEnvironment

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "Setup environment for tests"
        env:
          MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
          TEST_PORT: ${{ vars.TEST_PORT }}
      - name: Use variables
        run: |
          echo "database variable : $MONGO_TEST_URI"
          echo "port variable : $TEST_PORT"
      - run: npm run test-ci
